[package]
name = "rarena-allocator"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
homepage = "https://github.com/al8n/rarena/tree/main/allocator"
documentation = "https://docs.rs/rarena-allocator"
description = "Lock-free ARENA allocator which can be used in both memory and on-disk."
license.workspace = true
rust-version.workspace = true
categories = ["data-structures", "memory-management", "concurrency", "no-std"]
keywords = ["arena", "lock-free"]

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = ["std"]
alloc = []
std = ["byteorder", "either/default"]
memmap = ["memmap2", "fs4", "std"]

[dependencies]
byteorder = { version = "1", optional = true }
crossbeam-utils.workspace = true 
either = { version = "1", default-features = false }
paste = "1"

fs4 = { version = "0.8", optional = true }
memmap2 = { version = "0.9", optional = true }

loom = { version = "0.7", optional = true }

[dev-dependencies]
tempfile = "3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
